name: 'PullRequest Test Coverage Report'
description: 'Reports test coverage summary of each pull-requests touched files in the description'
inputs:
  token: # id of input
    description: 'GITHUB Token'
    required: true
  path:
    description: 'Path to the coverage json file'
    required: true
  title:
    description: 'Title of the report summary'
    required: true
outputs:
  summary: # id of output
    description: 'Summary of the report as a json object'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'align-left'
  color: 'purple'
